### ISSUE TITLE
Cache buster worker

### ISSUE THREAD

**Issue by auro1** [slushie/laravel-assetic#13]
Hi.

Is there currently any way to get a cache busting URL?? (for long expiration times) apart from manually giving it a version number

**Comment by slushie** [comment]
I’ve pushed a commit which will give you options via the Asset::url() method. Try:

		<?php echo Asset::url(‘scripts’, array(‘md5’ => true)); ?>

to output an URL such as “/scripts.js?4f45b508fd5f54353901c6fdda1f36f6"

**Comment by tonglil** [comment]
Confirmed to be working.
